# ====================================
# 模版 / template

template_keepalived_config: "keepalived/keepalived.conf.j2"

# ====================================
# 文件 / file
# -- 指在Ansible服务端的文件

# KeepAlived 安装介质
file_keepalived_install_media: "install_media/keepalived-2.0.20.tar.gz"

# ====================================
# 路径 / path
# -- 指要发送到远端服务器的文件的绝对路径

# KeepAlived源码包安装日志 / configure
path_keepalived_install_log_configure: "{{ directory_keepalived_install_log }}/keepalived_source_install-configure.log"

# KeepAlived源码包安装日志 / make
path_keepalived_install_log_make: "{{ directory_keepalived_install_log }}/keepalived_source_install-make.log"

# KeepAlived源码包安装日志 / make install
path_keepalived_install_log_make_install: "{{ directory_keepalived_install_log }}/keepalived_source_install-make_install.log"

# KeepAlived配置文件
path_keepalived_config_sample: "{{ directory_keepalived_base }}/etc/keepalived/keepalived.conf"
path_keepalived_config: "{{ directory_keepalived_config }}/keepalived.conf"

# KeepAlived启动脚本变量文件
path_keepalived_systemctl_variable_sample: "{{ directory_keepalived_base }}/etc/sysconfig/keepalived"
path_keepalived_systemctl_variable: "/etc/sysconfig/keepalived"

# KeepAlived主程序
path_keepalived_sbin_sample: "{{ directory_keepalived_base }}/sbin/keepalived"
path_keepalived_sbin: "/usr/sbin/keepalived"

# ====================================
# 文件夹 / directory


# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ 需要修改的部分 / Begin

# ====================================
# KeepAlived / 参数配置

# KeepAlived 路由ID
keepalived_virtual_router_id: 52

# VIP 资源
keepalived_virtual_ip: "192.168.232.10"

# KeepAlived VIP 绑定到哪块网卡上
keepalived_nic_name: "ens32"

# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ 需要修改的部分 / Finished
