# 创建Linux系统组
- name: 创建Linux系统组
  group:
    # 用户组名称
    name: "{{ item['group_name'] }}"
    # 用户组ID
    gid: "{{ item['gid'] }}"
    state: present
  with_items:
    - "{{ list_linux_group }}"

# 创建Linux系统用户
- name: 创建Linux系统用户
  user:
    # 用户名
    name: "{{ item['username'] }}"
    # 用户ID
    uid: "{{ item['uid'] }}"
    # 用户组
    group: "{{ item['group'] }}"
    # 用户附加组
    groups: "{{ item['groups'] }}"
    append: yes
    # 用户口令
    password: "{{ item['password'] | password_hash('sha512') }}"
    # 是否创建家目录
    create_home: yes
    # 家目录在哪里
    home: "{{ item['dir_home'] }}"
    # 是否生成SSH密钥 / 可以用于SSH免密
    #generate_ssh_key: yes
    # SSH密钥长度
    #ssh_key_bits: 2048
    # SSH密钥文件存放在哪里
    #ssh_key_file: .ssh/id_rsa
    # 用户的默认SHELL程序
    shell: "{{ item['shell'] }}"
    # 用户注释
    comment: "{{ item['comment'] }}"
  # 从变量文件中获取可以迭代的创建用户数组
  with_items:
    - "{{ list_linux_user }}"

# SSH等价
# 将固定的密钥与公钥文件上传到目标服务器的目标位置
- name: MHA的操作系统管理用户的【私钥】
  copy:
    backup: yes
    owner: "{{ mha_linux_user }}"
    group: "{{ mha_linux_user }}"
    mode: 0600
    src: "{{ file_ssh_nopassword_key_private }}"
    dest: "{{ directory_ssh_nopasswd }}"

- name: MHA的操作系统管理用户的【公钥】
  copy:
    backup: yes
    owner: "{{ mha_linux_user }}"
    group: "{{ mha_linux_user }}"
    mode: 0644
    src: "{{ file_ssh_nopassword_key_public }}"
    dest: "{{ directory_ssh_nopasswd }}"

- name: MHA的操作系统管理用户的【已授权公钥文件】
  copy:
    backup: yes
    owner: "{{ mha_linux_user }}"
    group: "{{ mha_linux_user }}"
    mode: 0600
    src: "{{ file_ssh_nopassword_authorized_keys }}"
    dest: "{{ directory_ssh_nopasswd }}"

# 配置用户的sudo权限
- name: MHA的操作系统用户【sudo】
  shell: "echo '{{ mha_linux_user }} ALL=(ALL) NOPASSWD: ALL' | tee /etc/sudoers.d/{{ mha_linux_user }}"

- name: "修改sudo文件权限"
  shell: "chmod 0440 /etc/sudoers.d/{{ mha_linux_user }}"

# 创建上传脚本的目录
- name: 创建上传SSH用户免密后续脚本的目录
  file:
    path: "{{ directory_mha_script }}"
    owner: "{{ mha_linux_user }}"
    group: "{{ mha_linux_user }}"
    mode: 0755
    state: directory

# 上传自动创建SSH用户known_hosts脚本
- name: 上传SSH用户自动创建known_hosts的脚本
  template:
    backup: yes
    src: "{{ template_after_ssh_nopasswd }}"
    dest: "{{ path_after_ssh_nopasswd }}"
    owner: "{{ mha_linux_user }}"
    group: "{{ mha_linux_user }}"
    mode: 0755

# 自动创建用户的known_hosts文件记录
# -- 如果不创建，会影响后面do_mha.sh的远程自动修复
# -- 有可能重复执行该脚本，因此需要忽略错误，否则会影响后续步骤的任务的执行
- name: 自动创建MHA操作系统用户的【known_hosts】
  shell: "su - {{ mha_linux_user }} -c 'sh {{ path_after_ssh_nopasswd }}'"
  ignore_errors: yes
