# ====================================
# 模板 / template

# MHA 默认配置文件
template_cnf_masterha_default: "mha_config_file/masterha_default.cnf.j2"

# MHA 应用配置文件
template_cnf_app: "mha_config_file/app.cnf.j2"

# 需要上传到MHA脚本目录的文件

# -- MHA 故障切换脚本
template_mha_script_master_ip_failover: "mha_extension_script/master_ip_failover.j2"

# -- MHA 扩展脚本
template_mha_extension_script_call_do_mha: "mha_extension_script/call_do_mha.sh.j2"
template_mha_extension_script_do_mha: "mha_extension_script/do_mha.sh.j2"

# 这个脚本要上传到特定目录
template_mha_extension_script_HealthCheck: "mha_extension_script/HealthCheck.pm.j2"

# ====================================
# 文件 / file
# -- 指在Ansible服务端的文件

# MHA 安装介质
# --- Manager
file_mha_install_media_manager: "install_media/mha4mysql-manager-0.58-0.el7.centos.noarch.rpm"
# --- Node
file_mha_install_media_node: "install_media/mha4mysql-node-0.58-0.el7.centos.noarch.rpm"

# 故障切换脚本
# -- 因为包含自定义的脚本部分，所以最好是用模板的形式，而不是文件的形式
#file_mha_script_master_ip_failover: "mha/master_ip_failover"

# 在线迁移脚本
file_mha_script_master_ip_online_change: "mha/master_ip_online_change"

# 电源管理脚本
file_mha_script_power_manager: "mha/power_manager"

# 通知脚本
file_mha_script_send_report: "mha/send_report"

# ====================================
# 路径 / path
# -- 指要发送到远端服务器的文件的绝对路径

# MHA 全局默认配置文件
path_cnf_masterha_default: "/etc/masterha_default.cnf"

# MHA 应用配置文件
path_cnf_app: "{{ directory_mha_config }}/{{ mha_conf_app_name }}.cnf"

# MHA 日志文件
# 如果需要修改这个文件名，则需要成对修改关联的几个脚本中的文件名
# -- 与具体的应用的配置文件相关
# -- 也与自定义的MHA的扩展脚本有关
path_mha_manager_log: "{{ directory_mha_log }}/{{ mha_conf_app_name }}.log"

# 故障切换脚本
path_mha_script_master_ip_failover: "{{ directory_mha_script }}/master_ip_failover"

# 在线迁移脚本
path_mha_script_master_ip_online_change: "{{ directory_mha_script }}/master_ip_online_change"

# MHA 扩展脚本
# -- 扩展脚本也上传到MHA的脚本目录中
path_mha_extension_script_call_do_mha: "{{ directory_mha_script }}/call_do_mha.sh"
path_mha_extension_script_do_mha: "{{ directory_mha_script }}/do_mha.sh"

# 这个脚本的路径一般是固定的
# 如果不放心，可以通过系统命令实时获取
# find / -name "HealthCheck.pm"
path_mha_extension_script_HealthCheck: "/usr/share/perl5/vendor_perl/MHA/HealthCheck.pm"

# ====================================
# 文件夹 / directory

# ====================================
# 列表

# 扩展脚本模板与目标位置
list_template_mha_script:
  - template: "{{ template_mha_script_master_ip_failover }}"
    path: "{{ path_mha_script_master_ip_failover }}"
  - template: "{{ template_mha_extension_script_call_do_mha }}"
    path: "{{ path_mha_extension_script_call_do_mha }}"
  - template: "{{ template_mha_extension_script_do_mha }}"
    path: "{{ path_mha_extension_script_do_mha }}"
  - template: "{{ template_mha_extension_script_HealthCheck }}"
    path: "{{ path_mha_extension_script_HealthCheck }}"

# 安装介质：管理端
list_mha_install_media_manager:
  - "{{ file_mha_install_media_manager }}"
  - "{{ file_mha_install_media_node }}"

# 安装介质：成员端
list_mha_install_media_node:
  - "{{ file_mha_install_media_node }}"

# MHA 脚本 / 调用列表
list_mha_script:
  #- "{{ file_mha_script_master_ip_failover }}"
  - "{{ file_mha_script_master_ip_online_change }}"
  - "{{ file_mha_script_power_manager }}"
  - "{{ file_mha_script_send_report }}"

# YUM软件包
list_rpm_package:
  - perl-Config-Tiny
  - perl-Email-Date-Format
  - perl-File-Remove
  - perl-Log-Dispatch
  - perl-Mail-Sender
  - perl-Mail-Sendmail
  - perl-MIME-Lite
  - perl-MIME-Types
  - perl-Module-Install
  - perl-Module-ScanDeps
  - perl-Parallel-ForkManager
  - perl-YAML
  - perl-DBD-MySQL
  - perl-DBI
  - mysql-libs

# ====================================
# 主机信息

# -- 涉及到的服务器
mysql_replication:
  server1:
    host: "{{ host_info[0].ip }}"
    hostname: "{{ host_info[0].name }}"
    port: 3306
  server2:
    host: "{{ host_info[1].ip }}"
    hostname: "{{ host_info[1].name }}"
    port: 3306

# MHA管理节点
mha_manager_host: "{{ host_info[2].ip }}"
mha_manager_hostname: "{{ host_info[2].ip }}"

# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ 需要修改的部分 / Begin

# ====================================
# 用户：操作系统

# -- MHA的Linux管理用户
# -- MHA所有的成员主机上面都需要有MHA管理用户
# -- 并且配置了SUDO权限与SSH等价
# -- MHA扩展脚本：依赖该用户
mha_linux_user: "mha"
mha_linux_user_password: "oracle"

# ====================================
# 用户：数据库

# -- 数据库用户 / 用于主从复制的用户
mysql_replication_user_name: "repl"
mysql_replication_user_password: "oracle"

# -- 数据库用户 / MHA
mysql_mha_user_name: "mha"
mysql_mha_user_password: "oracle"

# ====================================
# MySQL MHA 相关参数
# -- 不同的环境，只需要修改这里的配置

# 当前脚本在同一个MHA Manager节点上第几次运行
# - 如果在同一个MHA Manager节点上第二次运行，需要改成【2】，以此类推
# - 如果在不同的MHA Manager节点上第一次运行，则该参数必须为【1】
# ----------------
# - 该参数影响脚本实际执行行为，务必按照上述规则正确配置
mha_install_time: 1

# 应用配置文件名称
# --- 默认按照执行次数去命名应用配置文件名
mha_conf_app_name: "app_{{ mha_install_time }}"

# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ 需要修改的部分 / Finished
