# MySQL 管理账号口令（root@localhost用户）

# 从MySQL的错误日志文件中找到临时口令
# -- 有可能同一个机器执行多次，所以为了等幂性，找寻临时口令的时候要准确一点，只找寻满足特征值的最后一行
- name: 从MySQL的错误日志中找到临时口令
  shell: cat {{ path_mysql_error_log }} | grep "A temporary password is generated for" | tail -n 1 | awk '{print $NF}'
  register: mysql_database_user_root_password_temporary

# 显示一下临时口令
- name: MySQL数据库第一次启动时生成的临时口令
  debug:
    msg: "{{ mysql_database_user_root_password_temporary['stdout'] }}"

# 通过得到的临时口令，修改数据库的口令为变量文件中设置的口令
- name: 修改MySQL的临时口令
  shell: "mysqladmin -h localhost -u root -p'{{ mysql_database_user_root_password_temporary['stdout'] }}' password '{{ mysql_database_user_root_password }}'"
  ignore_errors: yes
  notify: "mysql user root@localhost password has been changed."

# MySQL 其他账号口令（非root@localhost用户）
# -- 创建MySQL数据库内的其他用户与口令

- name: 创建MySQL数据库用户
  mysql_user:
    # ----- 登陆数据库
    login_host: "localhost"
    login_port: 3306
    login_user: root
    login_password: "{{ mysql_database_user_root_password }}"
    # ----- 创建的用户的信息
    name: "{{ item['username'] }}"
    host: "{{ item['host'] }}"
    password: "{{ item['password'] }}"
    priv: "{{ item['priv'] }}"
    # -----
    state: present
  with_items:
    - "{{ list_mysql_user }}"
